// config/index.tsx
import { cookieStorage, createStorage } from 'wagmi' // Use 'wagmi' directly (Wagmi v2+)
import { WagmiAdapter } from '@reown/appkit-adapter-wagmi'
import { base } from '@reown/appkit/networks'
import { coinbaseWallet, metaMask, walletConnect } from '@wagmi/connectors'
import type { Chain } from 'viem' // Import Chain type for explicit typing

// WalletConnect / Reown project id used across the app. The value is public by design,so provide a
// safe default to keep the site functional even if the env var is missing in a new environment.
const DEFAULT_PROJECT_ID = '298f0ec5e03b7dd2a082de73a5e226b7'

// Read Project ID from environment variables with a fallback
export const projectId = process.env.NEXT_PUBLIC_PROJECT_ID || DEFAULT_PROJECT_ID

// Log once in development if the fallback is being used, so we remember to wire envs later.
if (process.env.NODE_ENV !== 'production' && projectId === DEFAULT_PROJECT_ID) {
  console.warn('Using default NEXT_PUBLIC_PROJECT_ID fallback. Set it in .env.local to override.')
}

// Define supported networks - Base only for VMF
export const networks: [Chain, ...Chain[]] = [base] // Base network only for VMF token

const dappMetadata = {
  name: 'VMF - Veterans & Military Families',
  description: 'Supporting those who served through blockchain technology',
  url: 'https://vmfcoin.com',
  icons: ['https://vmfcoin.com/favicon.png'],
}

// Create the Wagmi adapter instance with explicit configuration
export const wagmiAdapter = new WagmiAdapter({
  storage: createStorage({ storage: cookieStorage }), // Use cookieStorage for SSR
  ssr: true, // Enable SSR support
  projectId,
  networks, // Pass the explicitly typed networks array
  connectors: [
    coinbaseWallet({
      appName: dappMetadata.name,
      appLogoUrl: dappMetadata.icons[0],
      preference: 'smartWalletOnly', // This enables the embedded wallet experience
    }),
    metaMask({
      dappMetadata,
    }),
    walletConnect({
      projectId,
      metadata: dappMetadata,
      showQrModal: false,
    }),
  ],
})

// Export the Wagmi config generated by the adapter
export const config = wagmiAdapter.wagmiConfig
