[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.23"
rpc_url = "https://sepolia.base.org"
optimizer = true
optimizer_runs = 200
evm_version = "cancun"
via_ir = true
fs_permissions = [{ access = "read", path = "./holders.json"}]
 
[rpc_endpoints]
base = "https://mainnet.base.org"
baseSepolia = "https://sepolia.base.org"
 
[etherscan]
baseSepolia = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }
base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }
